// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"CustomLogo","status":true,"description":"Shows RPG Maker and user logos at the start of the game.","parameters":{"logo1":"","logo1ImageName":"MadeWithMv","logo1Skippable":"true","logo1Coordinate":"","logo1X":"408","logo1Y":"312","logo1Origin":"0.5","logo1Time":"","logo1FadeinFrames":"12","logo1FadeoutFrames":"12","logo1DurationFrames":"120","logo2":"","logo2ImageName":"","logo2Skippable":"true","logo2Coordinate":"","logo2X":"408","logo2Y":"312","logo2Origin":"0.5","logo2Time":"","logo2FadeinFrames":"12","logo2FadeoutFrames":"12","logo2DurationFrames":"120","logo3":"","logo3ImageName":"","logo3Skippable":"true","logo3Coordinate":"","logo3X":"408","logo3Y":"312","logo3Origin":"0.5","logo3Time":"","logo3FadeinFrames":"12","logo3FadeoutFrames":"12","logo3DurationFrames":"120","allowTotalSkip":"true"}},
{"name":"QuestionaryTesisJosh","status":false,"description":"","parameters":{}},
{"name":"HPpartylostupdate","status":true,"description":"Registra toda la vida que pierde la party del jugador y la guarda en una variable.","parameters":{"VariableID":"11"}},
{"name":"NumOfDeath","status":true,"description":"Cuenta cuántas veces un miembro de la party llega a 0 HP y lo guarda en una variable.","parameters":{"VariableID":"12"}},
{"name":"NumofHitsplayer","status":true,"description":"Cuenta cuántas veces un miembro de la party recibe un golpe (físico o mágico) y lo guarda en una variable.","parameters":{"VariableID":"13"}},
{"name":"QuestionaryTesisJosh","status":true,"description":"Manda las respuestas del cuestionarios a un servidor.","parameters":{"VariableID":"10"}},
{"name":"Current_Turn","status":true,"description":"Guarda el número de turno actual de batalla en una variable del juego. Se actualiza al inicio de cada turno.","parameters":{"TurnVariableID":"14"}},
{"name":"Enemies_AI","status":true,"description":"Logger RNEAT basado en variables 11-14 para entradas personalizadas del jugador (RPG Maker MV), ejecutado cada 3 turnos ✨📊\r\nGuarda directamente en una carpeta externa para uso en Python.","parameters":{}},
{"name":"Enemylevel","status":false,"description":"Escala las stats base de todos los enemigos para simular un nivel fijo.","parameters":{}}
];
